DROP TABLE IF EXISTS user_table;

CREATE TABLE user_table (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    birthday TEXT NOT NULL,
    password TEXT NOT NULL,
    seeking TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);